#!/usr/bin/env python
import sys

_usage = "stou <s1> <s2> ..."
_version = "Thu May 16 17:23:01 JST 2024"
_code = "tairar Commands (LINUX/PYTHON3.10/UTF-8)"

def usage():
    print("Usage   :", _usage, file=sys.stderr)
    print("Version :", _version, file=sys.stderr)
    print("         ", _code, file=sys.stderr)
    sys.exit(1)

if __name__ == '__main__':
    argc = len(sys.argv)
    if argc < 2:
        usage()
    output = ""
    for i in range(1, argc):
        if i != 1:
            output += '_'
        output += sys.argv[i]
    print(output)
    sys.exit(0)
